import sys
from pathlib import Path
import os
import requests

# Bootstrap imports
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from utils.paths import FINAL_VIDEO_FILE, METADATA_FILE
from utils.logger import get_logger
from utils.helpers import load_json
from automation.database.connection import get_facebook_conn
from python.meta_auth import get_valid_token, get_page_access_token, load_credentials

logger = get_logger("facebook.upload")

def upload_facebook_reel(video_path: Path, title: str, description: str) -> str | None:
    """Uploads a Reel to Facebook Page using the Meta Graph API v25.0 resumable upload protocol."""
    try:
        creds = load_credentials()
        page_id = creds.get("page_id")
        if not page_id:
            logger.warning("Facebook Page ID is missing.")
            return None
            
        user_token = get_valid_token()
        page_token = get_page_access_token(user_token, page_id)
        if not page_token:
            logger.warning("Failed to obtain Facebook Page access token.")
            return None

        # Phase 1: Start Session
        logger.info("Facebook Reels upload: Phase 1 (Starting session)...")
        version = creds.get("graph_api_version", "v25.0")
        base_url = creds.get("graph_base_url", "https://graph.facebook.com")
        
        start_url = f"{base_url}/{version}/{page_id}/video_reels"
        start_payload = {
            "upload_phase": "start",
            "access_token": page_token
        }
        
        response = requests.post(start_url, data=start_payload, timeout=60)
        res_data = response.json()
        
        video_id = res_data.get("video_id")
        upload_url = res_data.get("upload_url")
        
        if not video_id or not upload_url:
            raise Exception(f"Phase 1 start failed: {res_data}")

        # Phase 2: Upload Video File Binary
        logger.info(f"Facebook Reels upload: Phase 2 (Uploading file binary to {upload_url})...")
        file_size = video_path.stat().st_size
        
        headers = {
            "Authorization": f"OAuth {page_token}",
            "offset": "0",
            "file_size": str(file_size),
            "Content-Type": "application/octet-stream"
        }
        
        with open(video_path, "rb") as f:
            upload_response = requests.post(upload_url, headers=headers, data=f, timeout=120)
            
        upload_res_data = upload_response.json()
        if "success" not in upload_res_data and not upload_res_data.get("success", False):
            # Check if there is an error
            if "error" in upload_res_data or upload_response.status_code != 200:
                raise Exception(f"Phase 2 upload binary failed: {upload_res_data}")

        # Phase 3: Finish Session
        logger.info("Facebook Reels upload: Phase 3 (Finishing session)...")
        finish_url = f"{base_url}/{version}/{page_id}/video_reels"
        finish_payload = {
            "upload_phase": "finish",
            "video_id": video_id,
            "title": title[:100],
            "description": description[:5000],
            "video_state": "PUBLISHED",
            "access_token": page_token
        }
        
        finish_response = requests.post(finish_url, data=finish_payload, timeout=60)
        finish_res_data = finish_response.json()
        
        if "success" not in finish_res_data and not finish_res_data.get("success", False):
            if "error" in finish_res_data:
                raise Exception(f"Phase 3 finish failed: {finish_res_data}")
                
        # The Facebook Reels URL is computed using the page ID and the video ID
        post_url = f"https://www.facebook.com/{page_id}/videos/{video_id}"
        logger.info(f"Reel upload completed! Watch here: {post_url}")
        
        return post_url
        
    except Exception as e:
        logger.error(f"Facebook upload failed: {e}", exc_info=True)
        return None

def run() -> str | None:
    if not FINAL_VIDEO_FILE.exists():
        logger.error(f"Final video file not found: {FINAL_VIDEO_FILE}")
        return None

    try:
        metadata = load_json(METADATA_FILE)
        title = metadata.get("title", "AI Generated Reels")
        description = metadata.get("description", "A video generated by the Shortest Orbit V3 engine.")
        
        post_url = upload_facebook_reel(FINAL_VIDEO_FILE, title, description)
        
        if post_url:
            fb_id = post_url.rstrip("/").split("/")[-1]
            try:
                conn = get_facebook_conn()
                cursor = conn.cursor()
                cursor.execute("""
                    UPDATE videos SET facebook_url = ?, facebook_id = ?, status = 'uploaded', uploaded_at = CURRENT_TIMESTAMP
                    WHERE id = (SELECT MAX(id) FROM videos WHERE status = 'generating')
                """, (post_url, fb_id))
                conn.commit()
                conn.close()
                logger.info(f"Database facebook_url updated to: {post_url}")
            except Exception as e:
                logger.error(f"Failed to update facebook.db: {e}")
                
            return post_url
    except Exception as e:
        logger.error(f"Facebook upload runner error: {e}")
        
    return None

if __name__ == "__main__":
    url = run()
    if url:
        print(f"Facebook Upload Success: {url}")
    else:
        print("Facebook Upload Failed")
